# COPY and this file to secrets.yml and modify as needed
development:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/development.db
  MSG_KEY: W1QmmrmXut08/9NrY73j/ZVxXOGDWDqwu6lXPAIeYJs=
  DB_KEY: VPlfRCNk5W+qe49lIw38Oeipa02AMzDH4dq5N/rrSZw=
  SIGNING_KEY: 7duW3iZtXarA6aNx4Z13xjLY8dQmhg9LDOzh6NUReRw=
  VERIFY_KEY: wbzi/N3ztqaEq9479eaJtnH7v77xP5Ca0QQvCA8gHY0=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GOOGLE_ACCOUNT_URL: https://console.cloud.google.com/apis

test:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/test.db
  MSG_KEY: W1QmmrmXut08/9NrY73j/ZVxXOGDWDqwu6lXPAIeYJs=
  DB_KEY: VPlfRCNk5W+qe49lIw38Oeipa02AMzDH4dq5N/rrSZw=
  SIGNING_KEY: 7duW3iZtXarA6aNx4Z13xjLY8dQmhg9LDOzh6NUReRw=
  VERIFY_KEY: wbzi/N3ztqaEq9479eaJtnH7v77xP5Ca0QQvCA8gHY0=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GOOGLE_ACCOUNT_URL: https://console.cloud.google.com/apis

production:
  DATABASE_URL: <do not edit - allow production server to set>
  MSG_KEY: <`rake newkey:msg`>
  DB_KEY: hJOOwsk1/s/845IcMokltv3vL8X9r0aLwxfDd3FARpQ= #<`rake newkey:db`>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GOOGLE_ACCOUNT_URL: https://console.cloud.google.com/apis
